### ISSUE TITLE
Merge conflict present in rss.xml page

### ISSUE THREAD

**Issue by brettchalupa** [webhook/webhook-theme-podcast#1]
In [`pages/rss.xml` on lines 31 to 45](https://github.com/webhook/webhook-theme-podcast/blob/master/pages/rss.xml#L31-L45) there seems to be the remains of a merge conflict present. I am guessing it should be removed (which I am happy to help with), but which is correct? The HEAD or 5e6aca8e01c0b2c95f75a3ff14dc1541483bd754?

It seems to have been introduced in https://github.com/webhook/webhook-theme-podcast/commit/2f364d74fc5bddad33b334003531eb1e8780bb08

**Comment by snide** [comment]
Thanks for the spot.
